let nombre= prompt ('entre your nombre entre 1 et 7')
if (nombre=="1") {alert('lundi')}
else{
    if (nombre=="2") {alert('mardi')}
    else{
        if (nombre=="3") {alert('mercredi')}
        else{
            if (nombre=="4") {alert('jeudi')}
            else{
                if ( nombre=="5") {alert('vendredi')}
                else{
                    if ( nombre=="6") {alert('samdi')}
                    else{
                        if ( nombre=="7") {alert('dimanche')}
                    }
                }
            }
        }
    }
}
{alert ('numéro invalide')}
